"""
Django settings for meusiite project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2&9f)@rxz0m4@8&rbe0h@b%jf@g*j5t5nm2jr$37urf!wpp&j*'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'core',
    'django_cleanup.apps.CleanupConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'meusiite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'meusiite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# --- Configurações do Painel Admin (Jazzmin) ---

JAZZMIN_SETTINGS = {
    # Títulos e Cabeçalhos
    "site_title": "Admin Green",
    "site_header": "Painel Gerencial",
    "site_brand": "Sua Marca",
    "welcome_sign": "Bem-vindo de volta, Administrador",
    "copyright": "Sua Empresa",

    # Menu Lateral (Sidebar)
    "show_sidebar": True,
    "navigation_expanded": True,

    # Ícones para as Apps (Usando FontAwesome)
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "core.Produto": "fas fa-box-open", # Ícone de caixa para produtos
    },
    
    # Ordem do menu lateral
    "order_with_respect_to": ["core", "auth"],
    "custom_css": "admin_custom.css",
}

# --- Personalização da Interface (Cores e Arredondamento) ---
JAZZMIN_UI_TWEAKS = {
    "theme": "flatly",   # Tema base limpo e moderno
    
    # Barra lateral (Verde escuro para contraste)
    "sidebar": "sidebar-dark-success", 
    
    # Cores principais
    "navbar": "navbar-success navbar-dark", # Barra do topo Verde
    "accent": "accent-success",             # Detalhes em verde
    "button_classes": {
        "primary": "btn-success",           # Botões principais verdes
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

import os

# URL para acessar as imagens no navegador
MEDIA_URL = '/media/'

# Pasta física no computador onde elas ficarão
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
